name: stampy
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pip
  - sqlite
  - pandas
  - pip:
      - lxml
      - black
      - discord-py
      - flask
      - gitpython
      - google-api-python-client
      - google-auth-oauthlib
      - jellyfish
      - openai
      - psutil
      - python-dotenv
      - slack-sdk
      - structlog
      - transformers
      - codaio
      - helicone
      - mypy
      - pylint
      - pandas-stubs
      - types-psutil
